In [12]:
import torch

In [13]:
x = torch.randn(3, requires_grad=True)
x

tensor([1.0438, 0.6930, 0.3999], requires_grad=True)

In [14]:
y = x + 2
y

tensor([3.0438, 2.6930, 2.3999], grad_fn=<AddBackward0>)

In [15]:
z = y * y * 2
z

tensor([18.5294, 14.5048, 11.5186], grad_fn=<MulBackward0>)

In [16]:
z = z.mean()
z

tensor(14.8509, grad_fn=<MeanBackward0>)

In [17]:
z.backward()
print(x.grad)

tensor([4.0584, 3.5907, 3.1998])
